### ISSUE TITLE
Ready yet?

### ISSUE THREAD

**Issue by i-am-the-slime** [paluh/purescript-boomboom#2]
I'm hot for this! Do you think I could use this already with Halogen?

**Comment by paluh** [comment]
@i-am-the-slime We are using it on our backend and it works nicely. I haven't done anything with it on the frontend (to be honest we are developing in Purescript mainly on the backend currently :-)).

The only caveat/deficiency in the current API is that records are encoded in alphabetical order of fields so you have to name fields appropriately if you care about order (in case of nested routes this could be the case).

 I'm going to push a short library guide in the form of literate tests soon. I hope till Sunday.

**Comment by paluh** [comment]
@i-am-the-slime I think that `routing-duplex` is much better choice right now. Please check it out!

**Comment by i-am-the-slime** [comment]
Nice, I am using it already since about when you wrote this :)
